// packages/vue/src/components/alert.vue
<script setup lang="ts">
import type { DisplayContent } from "./display-types";
import { RenderContent } from "./display-utils";
withDefaults(
  defineProps<{
    title?: DisplayContent;
    variant?: "info" | "success" | "warning" | "destructive";
    announce?: boolean;
    role?: string;
    className?: string;
  }>(),
  { variant: "info", announce: false },
);
</script>
<template>
  <div
    :class="['cr-alert', className]"
    :data-variant="variant"
    :role="role ?? (announce ? 'alert' : undefined)"
  >
    <strong v-if="title || $slots.title"
      ><slot name="title"><RenderContent :content="title" /></slot
    ></strong>
    <div v-if="$slots.default"><slot /></div>
  </div>
</template>

// packages/react/src/components/alert.tsx
"use client";
import type { HTMLAttributes, ReactNode } from "react";
import { cx } from "./utils";
export function Alert({
  title,
  variant = "info",
  announce = false,
  role,
  children,
  className,
  ...props
}: Omit<HTMLAttributes<HTMLDivElement>, "title"> & {
  title?: ReactNode;
  variant?: "info" | "success" | "warning" | "destructive";
  announce?: boolean;
}) {
  return (
    <div
      {...props}
      role={role ?? (announce ? "alert" : undefined)}
      className={cx("cr-alert", className)}
      data-variant={variant}
    >
      {title && <strong>{title}</strong>}
      {children && <div>{children}</div>}
    </div>
  );
}
