// packages/vue/src/components/collapsible.vue
<script setup lang="ts">
import {
  CollapsibleRoot,
  CollapsibleTrigger,
  CollapsibleContent,
} from "reka-ui";
import { useDisplayModel } from "./display-utils";
const props = withDefaults(
  defineProps<{
    title: string;
    defaultOpen?: boolean;
    open?: boolean;
    disabled?: boolean;
    keepMounted?: boolean;
  }>(),
  { defaultOpen: false, open: undefined, disabled: false, keepMounted: false },
);
const emit = defineEmits<{
  "update:open": [value: boolean];
  "open-change": [value: boolean];
}>();
const expanded = useDisplayModel(
  () => props.open,
  props.defaultOpen,
  (value) => {
    emit("update:open", value);
    emit("open-change", value);
  },
);
</script>
<template>
  <CollapsibleRoot
    v-model:open="expanded"
    :disabled="disabled"
    class="cr-collapsible"
    ><CollapsibleTrigger
      :as-child="!!$slots.trigger"
      class="cr-button cr-collapsible-trigger"
      data-variant="ghost"
      ><slot name="trigger"
        >{{ title
        }}<svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.75"
          aria-hidden="true"
        >
          <path d="m6 9 6 6 6-6" /></svg></slot></CollapsibleTrigger
    ><CollapsibleContent
      :force-mount="keepMounted || undefined"
      v-show="!keepMounted || expanded"
      class="cr-collapsible-panel"
      ><slot /></CollapsibleContent
  ></CollapsibleRoot>
</template>

// packages/react/src/components/collapsible.tsx
"use client";
import { Collapsible as Base } from "@base-ui/react/collapsible";
import type { ReactNode } from "react";
export function Collapsible({
  title,
  children,
  defaultOpen = false,
  open,
  onOpenChange,
  disabled = false,
  keepMounted = false,
}: {
  title: string;
  children: ReactNode;
  defaultOpen?: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  keepMounted?: boolean;
}) {
  return (
    <Base.Root
      defaultOpen={defaultOpen}
      open={open}
      onOpenChange={onOpenChange}
      disabled={disabled}
      className="cr-collapsible"
    >
      <Base.Trigger
        className="cr-button cr-collapsible-trigger"
        data-variant="ghost"
      >
        {title}
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.75"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </Base.Trigger>
      <Base.Panel keepMounted={keepMounted} className="cr-collapsible-panel">
        {children}
      </Base.Panel>
    </Base.Root>
  );
}
