// packages/vue/src/components/command.vue
<script setup lang="ts">
import { computed, ref, useId } from "vue";
import {
  ListboxRoot,
  ListboxFilter,
  ListboxContent,
  ListboxItem,
} from "reka-ui";
import Dialog from "./dialog.vue";
import { RenderContent, useDisplayModel } from "./display-utils";
import type { CommandItem, DisplayContent } from "./display-types";
const props = withDefaults(
  defineProps<{
    trigger?: DisplayContent;
    title?: string;
    items: CommandItem[];
    open?: boolean;
    defaultOpen?: boolean;
    searchLabel?: string;
    searchPlaceholder?: string;
    emptyMessage?: DisplayContent;
  }>(),
  {
    trigger: "Open commands",
    title: "Command menu",
    open: undefined,
    defaultOpen: false,
    searchLabel: "Search commands",
    searchPlaceholder: "Search commands…",
    emptyMessage: "No matching commands.",
  },
);
const emit = defineEmits<{
  "update:open": [value: boolean];
  "open-change": [value: boolean];
  select: [item: CommandItem];
}>();
const expanded = useDisplayModel(
  () => props.open,
  props.defaultOpen,
  (value) => {
    emit("update:open", value);
    emit("open-change", value);
    if (!value) search.value = "";
  },
);
const search = ref("");
const input = ref<InstanceType<typeof ListboxFilter>>();
const listId = `cr-command-list-${useId()}`;
const filtered = computed(() =>
  props.items.filter((item) =>
    `${item.label} ${item.description ?? ""}`
      .toLocaleLowerCase()
      .includes(search.value.toLocaleLowerCase()),
  ),
);
function select(value: unknown) {
  const item = props.items.find((item) => item.value === value);
  if (!item || item.disabled) return;
  item.onSelect?.();
  emit("select", item);
  expanded.value = false;
}
</script>
<template>
  <Dialog
    v-model:open="expanded"
    :trigger="trigger"
    :title="title"
    :initial-focus="() => input?.$el as HTMLInputElement"
    ><template v-if="$slots.trigger" #trigger><slot name="trigger" /></template
    ><ListboxRoot :model-value="null" @update:model-value="select"
      ><ListboxFilter
        ref="input"
        v-model="search"
        role="combobox"
        :aria-expanded="expanded"
        :aria-controls="listId"
        aria-autocomplete="list"
        :aria-label="searchLabel"
        :placeholder="searchPlaceholder"
        class="cr-input" /><ListboxContent
        :id="listId"
        :aria-label="title"
        class="cr-command-list"
        ><ListboxItem
          v-for="item in filtered"
          :key="item.value"
          :value="item.value"
          :disabled="item.disabled"
          class="cr-menu-item"
          ><span class="cr-command-item-text"
            ><span>{{ item.label }}</span
            ><small v-if="item.description" class="cr-description">{{
              item.description
            }}</small></span
          ></ListboxItem
        ></ListboxContent
      >
      <p v-if="!filtered.length" role="status" class="cr-description">
        <slot name="empty"
          ><RenderContent :content="emptyMessage"
        /></slot></p></ListboxRoot
  ></Dialog>
</template>

// packages/react/src/components/command.tsx
"use client";
import { Combobox as Base } from "@base-ui/react/combobox";
import { Dialog } from "./dialog";
import { useRef, useState, type ReactNode } from "react";
export interface CommandItem {
  value: string;
  label: string;
  description?: string;
  onSelect: () => void;
  disabled?: boolean;
}
export function Command({
  trigger = "Open commands",
  title = "Command menu",
  items,
  open,
  onOpenChange,
  defaultOpen = false,
  searchLabel = "Search commands",
  searchPlaceholder = "Search commands…",
  emptyMessage = "No matching commands.",
}: {
  trigger?: ReactNode;
  title?: string;
  items: CommandItem[];
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  defaultOpen?: boolean;
  searchLabel?: string;
  searchPlaceholder?: string;
  emptyMessage?: ReactNode;
}) {
  const [internal, setInternal] = useState(defaultOpen);
  const input = useRef<HTMLInputElement>(null);
  const setOpen = (value: boolean) => {
    if (open === undefined) setInternal(value);
    onOpenChange?.(value);
  };
  return (
    <Dialog
      trigger={trigger}
      title={title}
      open={open ?? internal}
      onOpenChange={setOpen}
      initialFocus={input}
    >
      <Base.Root
        items={items}
        inline
        open={open ?? internal}
        autoHighlight
        value={null}
        itemToStringLabel={(item: CommandItem) => item.label}
        onValueChange={(item: CommandItem | null) => {
          if (item && !item.disabled) {
            item.onSelect();
            setOpen(false);
          }
        }}
      >
        <Base.Input
          ref={input}
          className="cr-input"
          aria-label={searchLabel}
          placeholder={searchPlaceholder}
        />
        <Base.Empty className="cr-description">{emptyMessage}</Base.Empty>
        <Base.List className="cr-command-list">
          {(item: CommandItem) => (
            <Base.Item
              className="cr-menu-item"
              key={item.value}
              value={item}
              disabled={item.disabled}
            >
              <span className="cr-command-item-text">
                <span>{item.label}</span>
                {item.description && (
                  <small className="cr-description">{item.description}</small>
                )}
              </span>
            </Base.Item>
          )}
        </Base.List>
      </Base.Root>
    </Dialog>
  );
}
