// packages/vue/src/components/date-picker.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useId, watch } from "vue";
import {
  FocusScope,
  PopoverClose,
  PopoverContent,
  PopoverPortal,
  PopoverRoot,
  PopoverTrigger,
} from "reka-ui";
import { CalendarDays, X } from "@lucide/vue";
import Calendar from "./calendar.vue";
import {
  addCalendarDays,
  addCalendarMonths,
  calendarLabels,
  endOfCalendarMonth,
  isCalendarDateDisabled,
  isCalendarRangeAvailable,
  parseCalendarDate,
  startOfCalendarMonth,
  useCalendarToday,
  type CalendarValue,
  type DatePickerProps,
  type DatePickerShortcut,
} from "./calendar-utils";
import { cx, usePortalContainer } from "./utils";

const props = withDefaults(defineProps<DatePickerProps>(), {
  mode: "single",
  locale: "en",
  disabled: false,
  autoApply: true,
  inline: false,
  overlay: false,
  collisionPadding: 16,
  clearable: true,
  showInputs: true,
  shortcuts: true,
  separator: " – ",
  open: undefined,
  // Preserve the calendar defaults when forwarding optional Boolean props.
  excludeDisabled: true,
  monthSelection: true,
});
const emit = defineEmits<{
  "update:modelValue": [value: CalendarValue];
  valueChange: [value: CalendarValue];
  "update:open": [open: boolean];
  openChange: [open: boolean];
  monthChange: [month: string];
  selectionPendingChange: [pending: boolean];
}>();
const root = ref<HTMLDivElement>();
const calendar = ref<InstanceType<typeof Calendar>>();
const portalContainer = usePortalContainer();
const headingId = useId();
const errorId = useId();
const labels = computed(() => calendarLabels(props.locale, props.labels));
const label = computed(
  () =>
    props.label ??
    (props.mode === "range"
      ? labels.value.chooseRange
      : labels.value.chooseDate),
);
const placeholder = computed(() => props.placeholder ?? label.value);
const internal = ref<CalendarValue>(props.defaultValue ?? null);
const internalOpen = ref(false);
const chosen = computed(() =>
  props.modelValue !== undefined ? props.modelValue : internal.value,
);
const open = computed(
  () => (props.open ?? internalOpen.value) && !props.disabled,
);
const draft = ref<CalendarValue>(chosen.value);
const selectionPending = ref(false);
const calendarKey = ref(0);
const error = ref("");
const getStart = (value: CalendarValue) =>
  typeof value === "string" ? value : (value?.start ?? "");
const getEnd = (value: CalendarValue) =>
  value && typeof value === "object" ? value.end : "";
const startInput = ref(getStart(chosen.value));
const endInput = ref(getEnd(chosen.value));
function pendingChange(pending: boolean) {
  selectionPending.value = pending;
  emit("selectionPendingChange", pending);
}
function synchronize(value = chosen.value, resetCalendar = true) {
  draft.value = value;
  startInput.value = getStart(value);
  endInput.value = getEnd(value);
  error.value = "";
  pendingChange(false);
  if (resetCalendar) calendarKey.value++;
}
watch(
  [() => getStart(chosen.value), () => getEnd(chosen.value), () => props.mode],
  () => synchronize(chosen.value, false),
);
function setOpen(next: boolean) {
  if (next && props.disabled) return;
  if (next) synchronize();
  else {
    calendar.value?.cancelPendingSelection();
    pendingChange(false);
  }
  if (props.open === undefined) internalOpen.value = next;
  emit("update:open", next);
  emit("openChange", next);
}
// A parent may open the picker directly through v-model:open.
watch(open, (next, previous) => {
  if (next && !previous) synchronize();
  if (!next && previous) {
    calendar.value?.cancelPendingSelection();
    pendingChange(false);
  }
});
function resetForm() {
  const next =
    props.modelValue === undefined
      ? (props.defaultValue ?? null)
      : props.modelValue;
  if (props.modelValue === undefined) internal.value = next;
  synchronize(next);
  setOpen(false);
}
let removeReset: (() => void) | undefined;
function bindForm() {
  removeReset?.();
  const form = props.form
    ? document.getElementById(props.form)
    : root.value?.closest("form");
  if (!(form instanceof HTMLFormElement)) return;
  const reset = (event: Event) =>
    queueMicrotask(() => {
      if (!event.defaultPrevented) resetForm();
    });
  form.addEventListener("reset", reset);
  removeReset = () => form.removeEventListener("reset", reset);
}
onMounted(bindForm);
watch(() => props.form, bindForm, { flush: "post" });
onBeforeUnmount(() => removeReset?.());
function valid(value: CalendarValue) {
  if (!value) return true;
  if (typeof value === "object")
    return props.mode === "range" && isCalendarRangeAvailable(value, props);
  try {
    parseCalendarDate(value);
  } catch {
    return false;
  }
  return props.mode !== "range" && !isCalendarDateDisabled(value, props);
}
function commit(value: CalendarValue) {
  if (props.disabled || !valid(value)) return;
  const next =
    props.mode === "range"
      ? value && typeof value === "object"
        ? value
        : null
      : typeof value === "string"
        ? value
        : "";
  if (props.modelValue === undefined) internal.value = next;
  emit("update:modelValue", next);
  emit("valueChange", next);
}
function select(value: CalendarValue, close = true, resetCalendar = false) {
  if (props.disabled) return;
  if (!valid(value)) {
    error.value = labels.value.invalidDate;
    return;
  }
  const visible =
    props.autoApply && props.modelValue !== undefined ? chosen.value : value;
  synchronize(visible, resetCalendar);
  if (props.autoApply) {
    commit(value);
    if (!props.inline && close) setOpen(false);
  }
}
function edit(start: string, end: string) {
  if (props.disabled) return;
  startInput.value = start;
  endInput.value = end;
  const next =
    props.mode === "range" ? (start && end ? { start, end } : null) : start;
  if ((props.mode === "range" && !!start !== !!end) || !valid(next)) {
    error.value = labels.value.invalidDate;
    return;
  }
  error.value = "";
  draft.value = next;
  pendingChange(false);
  calendarKey.value++;
  if (props.autoApply) commit(next);
}
function finishInput() {
  if (props.autoApply && props.modelValue !== undefined && !error.value) {
    startInput.value = getStart(chosen.value);
    endInput.value = getEnd(chosen.value);
  }
}
function cancel() {
  synchronize();
  if (!props.inline) setOpen(false);
}
function apply() {
  if (selectionPending.value || error.value) return;
  commit(draft.value);
  if (!props.inline) setOpen(false);
}
function escape(event: KeyboardEvent) {
  if (selectionPending.value) {
    event.preventDefault();
    calendar.value?.cancelPendingSelection();
  }
}
const format = (date: string) =>
  props.formatDate?.(date, props.locale) ??
  new Intl.DateTimeFormat(
    props.locale,
    props.dateFormat
      ? { ...props.dateFormat, timeZone: "UTC", calendar: "gregory" }
      : { dateStyle: "medium", timeZone: "UTC", calendar: "gregory" },
  ).format(parseCalendarDate(date));
const display = computed(() =>
  !chosen.value
    ? ""
    : typeof chosen.value === "string"
      ? format(chosen.value)
      : `${format(chosen.value.start)}${props.separator}${format(chosen.value.end)}`,
);
const localToday = useCalendarToday();
const items = computed(() => {
  const today = localToday.value || "1970-01-01",
    yesterday = addCalendarDays(today, -1);
  const lastMonth = startOfCalendarMonth(addCalendarMonths(today, -1));
  const defaults: DatePickerShortcut[] =
    props.mode === "range"
      ? [
          { label: labels.value.today, value: { start: today, end: today } },
          {
            label: labels.value.yesterday,
            value: { start: yesterday, end: yesterday },
          },
          {
            label: labels.value.last7Days,
            value: { start: addCalendarDays(today, -6), end: today },
          },
          {
            label: labels.value.last30Days,
            value: { start: addCalendarDays(today, -29), end: today },
          },
          {
            label: labels.value.thisMonth,
            value: {
              start: startOfCalendarMonth(today),
              end: endOfCalendarMonth(today),
            },
          },
          {
            label: labels.value.lastMonth,
            value: { start: lastMonth, end: endOfCalendarMonth(lastMonth) },
          },
        ]
      : [
          { label: labels.value.today, value: today },
          { label: labels.value.yesterday, value: yesterday },
        ];
  const shortcuts = Array.isArray(props.shortcuts)
    ? props.shortcuts
    : props.shortcuts
      ? defaults
      : [];
  return shortcuts.map((item: DatePickerShortcut) => {
    const value = typeof item.value === "function" ? item.value() : item.value;
    return {
      label: item.label,
      value,
      disabled:
        props.disabled ||
        (!localToday.value && !Array.isArray(props.shortcuts)) ||
        !valid(value),
    };
  });
});
const calendarValue = computed(() =>
  props.autoApply ? chosen.value : draft.value,
);
const common = computed(() => ({
  label: label.value,
  min: props.min,
  max: props.max,
  locale: props.locale,
  weekStartsOn: props.weekStartsOn,
  disabled: props.disabled,
  disabledDates: props.disabledDates,
  excludeDisabled: props.excludeDisabled,
  startFrom: props.startFrom,
  numberOfMonths: props.numberOfMonths,
  showWeekNumbers: props.showWeekNumbers,
  weekdayFormat: props.weekdayFormat,
  monthSelection: props.monthSelection,
  labels: props.labels,
  previousMonthLabel: props.previousMonthLabel,
  nextMonthLabel: props.nextMonthLabel,
  renderDay: props.renderDay,
}));
const contentAttributes = computed(() =>
  props.inline
    ? { role: "group", "aria-label": label.value }
    : {
        class: "cr-positioner cr-date-picker-positioner",
        align: "start" as const,
        sideOffset: 8,
        collisionPadding: props.collisionPadding,
        prioritizePosition: true,
        sticky: "always" as const,
        "aria-labelledby": headingId,
      },
);
const scopeAttributes = computed(() =>
  props.inline || props.overlay ? {} : { trapped: open.value, loop: true },
);
</script>

<template>
  <div ref="root" :class="cx('cr-date-picker', className)">
    <template v-if="name">
      <input
        type="hidden"
        :form="form"
        :name="mode === 'range' ? `${name}[start]` : name"
        :value="getStart(chosen)"
        :disabled="disabled"
      />
      <input
        v-if="mode === 'range'"
        type="hidden"
        :form="form"
        :name="`${name}[end]`"
        :value="getEnd(chosen)"
        :disabled="disabled"
      />
    </template>
    <PopoverRoot
      :open="open && !inline"
      :modal="overlay"
      @update:open="setOpen"
    >
      <PopoverTrigger
        v-if="!inline"
        :class="cx('cr-button cr-date-picker-trigger', triggerClassName)"
        data-variant="outline"
        data-size="md"
        :disabled="disabled"
        :aria-label="`${label}${display ? `: ${display}` : ''}`"
      >
        <slot
          name="trigger"
          :value="display"
          :placeholder="placeholder"
          :open="open"
        >
          <component
            :is="() => renderTrigger!(display, placeholder)"
            v-if="renderTrigger"
          />
          <template v-else>
            <span :data-placeholder="!display || undefined">{{
              display || placeholder
            }}</span>
            <slot name="icon"
              ><component :is="() => icon" v-if="icon" /><CalendarDays
                v-else
                :size="16"
                aria-hidden="true"
            /></slot>
          </template>
        </slot>
      </PopoverTrigger>
      <component
        :is="inline ? 'div' : PopoverPortal"
        v-bind="inline ? {} : { to: portalContainer }"
      >
        <div
          v-if="!inline && overlay && open"
          class="cr-date-picker-backdrop"
          aria-hidden="true"
        />
        <component
          :is="inline ? 'div' : PopoverContent"
          v-bind="contentAttributes"
          @escape-key-down="escape"
        >
          <component
            :is="inline || overlay ? 'div' : FocusScope"
            v-bind="scopeAttributes"
            :class="
              inline ? 'cr-date-picker-inline' : 'cr-popup cr-date-picker-popup'
            "
            @mount-auto-focus.prevent
            @unmount-auto-focus.prevent
          >
            <div v-if="!inline" class="cr-date-picker-heading">
              <h2 :id="headingId">{{ label }}</h2>
              <PopoverClose
                class="cr-date-picker-close"
                :aria-label="labels.close"
                ><X :size="16" aria-hidden="true"
              /></PopoverClose>
            </div>
            <div class="cr-date-picker-body">
              <div
                v-if="items.length"
                class="cr-date-picker-shortcuts"
                :aria-label="label"
              >
                <button
                  v-for="(item, index) in items"
                  :key="index"
                  type="button"
                  class="cr-button"
                  data-variant="ghost"
                  data-size="sm"
                  :disabled="item.disabled"
                  @click="select(item.value, true, true)"
                >
                  {{ item.label }}
                </button>
              </div>
              <div v-if="showInputs" class="cr-date-picker-inputs">
                <label>
                  <span>{{ mode === "range" ? labels.startDate : label }}</span>
                  <input
                    type="date"
                    :value="startInput"
                    :min="min ?? '0001-01-01'"
                    :max="max ?? '9999-12-31'"
                    :disabled="disabled"
                    :aria-invalid="!!error || undefined"
                    :aria-describedby="error ? errorId : undefined"
                    @blur="finishInput"
                    @change="
                      edit(($event.target as HTMLInputElement).value, endInput)
                    "
                  />
                </label>
                <label v-if="mode === 'range'">
                  <span>{{ labels.endDate }}</span>
                  <input
                    type="date"
                    :value="endInput"
                    :min="startInput || min || '0001-01-01'"
                    :max="max ?? '9999-12-31'"
                    :disabled="disabled"
                    :aria-invalid="!!error || undefined"
                    :aria-describedby="error ? errorId : undefined"
                    @blur="finishInput"
                    @change="
                      edit(
                        startInput,
                        ($event.target as HTMLInputElement).value,
                      )
                    "
                  />
                </label>
              </div>
              <Calendar
                ref="calendar"
                :key="calendarKey"
                v-bind="common"
                :mode="mode"
                :model-value="calendarValue"
                @update:model-value="select"
                @month-change="emit('monthChange', $event)"
                @selection-pending-change="pendingChange"
              >
                <template v-if="$slots.day" #day="slotProps"
                  ><slot name="day" v-bind="slotProps"
                /></template>
              </Calendar>
              <p
                v-if="error"
                :id="errorId"
                class="cr-date-picker-error"
                role="alert"
              >
                {{ error }}
              </p>
            </div>
            <div v-if="clearable || !autoApply" class="cr-date-picker-footer">
              <button
                v-if="clearable"
                type="button"
                class="cr-button"
                data-variant="ghost"
                data-size="sm"
                :disabled="disabled || (!startInput && !endInput)"
                @click="select(mode === 'range' ? null : '', false, true)"
              >
                {{ labels.clear }}
              </button>
              <div v-if="!autoApply" class="cr-date-picker-actions">
                <button
                  type="button"
                  class="cr-button"
                  data-variant="ghost"
                  data-size="sm"
                  :disabled="disabled"
                  @click="cancel"
                >
                  {{ labels.cancel }}
                </button>
                <button
                  type="button"
                  class="cr-button"
                  data-variant="primary"
                  data-size="sm"
                  :disabled="
                    disabled || selectionPending || !!error || !valid(draft)
                  "
                  @click="apply"
                >
                  {{ labels.apply }}
                </button>
              </div>
            </div>
          </component>
        </component>
      </component>
    </PopoverRoot>
  </div>
</template>

<style scoped>
/* Reka exposes the space beside the trigger on PopoverContent. The calendar
   body scrolls inside that space while the heading and actions stay visible. */
.cr-date-picker-popup.cr-popup {
  max-height: min(
    var(--reka-popover-content-available-height, 100dvh),
    calc(100dvh - 32px)
  );
  max-width: min(
    var(--reka-popover-content-available-width, 100vw),
    calc(100vw - 32px)
  );
}
</style>

// packages/react/src/components/date-picker.tsx
"use client";
import {
  useRef,
  useState,
  useEffect,
  useEffectEvent,
  type ReactNode,
} from "react";
import { Popover as Base } from "@base-ui/react/popover";
import { CalendarDays, X } from "lucide-react";
import {
  Calendar,
  parseCalendarDate,
  calendarLabels,
  useCalendarToday,
  addCalendarDays,
  addCalendarMonths,
  startOfCalendarMonth,
  endOfCalendarMonth,
  isCalendarDateDisabled,
  isCalendarRangeAvailable,
  type CalendarBaseProps,
  type DateRange,
} from "./calendar";
import { Button } from "./button";
import { cx, usePortalContainer } from "./utils";

type PickerValue = string | DateRange | null;
export type DatePickerShortcut = {
  label: string;
  value: string | DateRange | (() => string | DateRange);
};
export type DatePickerProps = CalendarBaseProps & {
  name?: string;
  form?: string;
  placeholder?: string;
  separator?: string;
  autoApply?: boolean;
  inline?: boolean;
  overlay?: boolean;
  clearable?: boolean;
  showInputs?: boolean;
  shortcuts?: boolean | readonly DatePickerShortcut[];
  formatDate?: (date: string, locale: string) => string;
  dateFormat?: Intl.DateTimeFormatOptions;
  triggerClassName?: string;
  icon?: ReactNode;
  renderTrigger?: (value: string, placeholder: string) => ReactNode;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
} & (
    | {
        mode?: "single";
        value?: string | null;
        defaultValue?: string;
        onValueChange?: (date: string) => void;
      }
    | {
        mode: "range";
        value?: DateRange | null;
        defaultValue?: DateRange;
        onValueChange?: (range: DateRange | null) => void;
      }
  );

export function DatePicker(props: DatePickerProps) {
  const {
    locale = "en",
    disabled = false,
    autoApply = true,
    inline = false,
    overlay = false,
    clearable = true,
    showInputs = true,
    shortcuts = true,
    separator = " – ",
    name,
    className,
    triggerClassName,
  } = props;
  const labels = calendarLabels(locale, props.labels),
    label =
      props.label ??
      (props.mode === "range" ? labels.chooseRange : labels.chooseDate);
  const placeholder = props.placeholder ?? label,
    container = usePortalContainer();
  const root = useRef<HTMLDivElement>(null);
  const [internal, setInternal] = useState<PickerValue>(
      props.defaultValue ?? null,
    ),
    [internalOpen, setInternalOpen] = useState(false);
  const chosen: PickerValue =
    props.value !== undefined ? props.value : internal;
  const [selectionPending, setSelectionPending] = useState(false);
  const [calendarKey, setCalendarKey] = useState(0);
  const [draft, setDraft] = useState<PickerValue>(chosen),
    [error, setError] = useState("");
  const getStart = (value: PickerValue) =>
    typeof value === "string" ? value : (value?.start ?? "");
  const getEnd = (value: PickerValue) =>
    typeof value === "object" && value ? value.end : "";
  const [startInput, setStartInput] = useState(getStart(chosen)),
    [endInput, setEndInput] = useState(getEnd(chosen));
  const synchronize = useEffectEvent(() => {
    setDraft(chosen);
    setStartInput(getStart(chosen));
    setEndInput(getEnd(chosen));
    setError("");
  });
  const chosenStart = getStart(chosen),
    chosenEnd = getEnd(chosen);
  useEffect(() => {
    synchronize();
  }, [chosenStart, chosenEnd]);
  const resetForm = useEffectEvent(() => {
    const next =
      props.value === undefined ? (props.defaultValue ?? null) : props.value;
    if (props.value === undefined) setInternal(next);
    setDraft(next);
    setStartInput(getStart(next));
    setEndInput(getEnd(next));
    setSelectionPending(false);
    setCalendarKey((current) => current + 1);
    setError("");
    if (props.open === undefined) setInternalOpen(false);
    props.onOpenChange?.(false);
  });
  useEffect(() => {
    const form = props.form
      ? document.getElementById(props.form)
      : root.current?.closest("form");
    if (!(form instanceof HTMLFormElement)) return;
    const reset = (event: Event) => {
      queueMicrotask(() => {
        if (!event.defaultPrevented) resetForm();
      });
    };
    form.addEventListener("reset", reset);
    return () => form.removeEventListener("reset", reset);
  }, [props.form]);
  const open = (props.open ?? internalOpen) && !disabled;
  function setOpen(next: boolean) {
    if (next && disabled) return;
    if (props.open === undefined) setInternalOpen(next);
    if (next) {
      setDraft(chosen);
      setStartInput(getStart(chosen));
      setEndInput(getEnd(chosen));
      setError("");
    }
    props.onOpenChange?.(next);
  }
  const options = {
    min: props.min,
    max: props.max,
    disabledDates: props.disabledDates,
    excludeDisabled: props.excludeDisabled,
  };
  function valid(value: PickerValue) {
    if (!value) return true;
    if (typeof value === "object")
      return props.mode === "range" && isCalendarRangeAvailable(value, options);
    try {
      parseCalendarDate(value);
    } catch {
      return false;
    }
    return props.mode !== "range" && !isCalendarDateDisabled(value, options);
  }
  function commit(value: PickerValue) {
    if (disabled || !valid(value)) return;
    if (props.value === undefined) setInternal(value);
    if (props.mode === "range")
      props.onValueChange?.(value && typeof value === "object" ? value : null);
    else props.onValueChange?.(typeof value === "string" ? value : "");
  }
  function select(value: PickerValue, close = true, resetCalendar = false) {
    if (disabled) return;
    if (!valid(value)) {
      setError(labels.invalidDate);
      return;
    }
    const visibleValue =
      autoApply && props.value !== undefined ? chosen : value;
    setDraft(visibleValue);
    setSelectionPending(false);
    if (resetCalendar) setCalendarKey((current) => current + 1);
    setStartInput(getStart(visibleValue));
    setEndInput(getEnd(visibleValue));
    setError("");
    if (autoApply) {
      commit(value);
      if (!inline && close) setOpen(false);
    }
  }
  function edit(start: string, end: string) {
    setStartInput(start);
    setEndInput(end);
    const next =
      props.mode === "range" ? (start && end ? { start, end } : null) : start;
    if ((props.mode === "range" && !!start !== !!end) || !valid(next)) {
      setError(labels.invalidDate);
      return;
    }
    setError("");
    setDraft(next);
    setSelectionPending(false);
    setCalendarKey((current) => current + 1);
    if (autoApply) commit(next);
  }
  function finishInput() {
    if (autoApply && props.value !== undefined && !error) {
      setStartInput(getStart(chosen));
      setEndInput(getEnd(chosen));
    }
  }
  const format = (date: string) =>
    props.formatDate?.(date, locale) ??
    new Intl.DateTimeFormat(
      locale,
      props.dateFormat
        ? { ...props.dateFormat, timeZone: "UTC", calendar: "gregory" }
        : { dateStyle: "medium", timeZone: "UTC", calendar: "gregory" },
    ).format(parseCalendarDate(date));
  const display = chosen
    ? typeof chosen === "string"
      ? format(chosen)
      : `${format(chosen.start)}${separator}${format(chosen.end)}`
    : "";
  const localToday = useCalendarToday();
  const today = localToday || "1970-01-01",
    yesterday = addCalendarDays(today, -1),
    thisMonth = startOfCalendarMonth(today),
    lastMonth = startOfCalendarMonth(addCalendarMonths(today, -1));
  const defaults: DatePickerShortcut[] =
    props.mode === "range"
      ? [
          { label: labels.today, value: { start: today, end: today } },
          {
            label: labels.yesterday,
            value: { start: yesterday, end: yesterday },
          },
          {
            label: labels.last7Days,
            value: { start: addCalendarDays(today, -6), end: today },
          },
          {
            label: labels.last30Days,
            value: { start: addCalendarDays(today, -29), end: today },
          },
          {
            label: labels.thisMonth,
            value: { start: thisMonth, end: endOfCalendarMonth(today) },
          },
          {
            label: labels.lastMonth,
            value: { start: lastMonth, end: endOfCalendarMonth(lastMonth) },
          },
        ]
      : [
          { label: labels.today, value: today },
          { label: labels.yesterday, value: yesterday },
        ];
  const items = Array.isArray(shortcuts)
    ? shortcuts
    : shortcuts
      ? defaults
      : [];
  const common: CalendarBaseProps = {
    label,
    min: props.min,
    max: props.max,
    locale,
    weekStartsOn: props.weekStartsOn,
    disabled,
    disabledDates: props.disabledDates,
    excludeDisabled: props.excludeDisabled,
    startFrom: props.startFrom,
    numberOfMonths: props.numberOfMonths,
    showWeekNumbers: props.showWeekNumbers,
    weekdayFormat: props.weekdayFormat,
    monthSelection: props.monthSelection,
    labels: props.labels,
    previousMonthLabel: props.previousMonthLabel,
    nextMonthLabel: props.nextMonthLabel,
    renderDay: props.renderDay,
    onMonthChange: props.onMonthChange,
    onSelectionPendingChange: (pending) => {
      setSelectionPending(pending);
      props.onSelectionPendingChange?.(pending);
    },
  };
  const fields =
    name &&
    (props.mode === "range" ? (
      <>
        <input
          type="hidden"
          form={props.form}
          name={`${name}[start]`}
          value={getStart(chosen)}
          disabled={disabled}
        />
        <input
          type="hidden"
          form={props.form}
          name={`${name}[end]`}
          value={getEnd(chosen)}
          disabled={disabled}
        />
      </>
    ) : (
      <input
        type="hidden"
        form={props.form}
        name={name}
        value={getStart(chosen)}
        disabled={disabled}
      />
    ));
  const calendarValue = autoApply ? chosen : draft;
  const content = (
    <>
      <div className="cr-date-picker-body">
        {items.length > 0 && (
          <div className="cr-date-picker-shortcuts" aria-label={label}>
            {items.map((item, index) => {
              const value =
                typeof item.value === "function" ? item.value() : item.value;
              return (
                <Button
                  key={index}
                  variant="ghost"
                  size="sm"
                  disabled={
                    disabled ||
                    (!localToday && !Array.isArray(shortcuts)) ||
                    !valid(value)
                  }
                  onClick={() => select(value, true, true)}
                >
                  {item.label}
                </Button>
              );
            })}
          </div>
        )}
        {showInputs && (
          <div className="cr-date-picker-inputs">
            <label>
              <span>{props.mode === "range" ? labels.startDate : label}</span>
              <input
                type="date"
                onBlur={finishInput}
                value={startInput}
                min={props.min ?? "0001-01-01"}
                max={props.max ?? "9999-12-31"}
                disabled={disabled}
                aria-invalid={!!error || undefined}
                onChange={(event) => edit(event.target.value, endInput)}
              />
            </label>
            {props.mode === "range" && (
              <label>
                <span>{labels.endDate}</span>
                <input
                  type="date"
                  onBlur={finishInput}
                  value={endInput}
                  min={startInput || props.min || "0001-01-01"}
                  max={props.max ?? "9999-12-31"}
                  disabled={disabled}
                  aria-invalid={!!error || undefined}
                  onChange={(event) => edit(startInput, event.target.value)}
                />
              </label>
            )}
          </div>
        )}
        <div>
          {props.mode === "range" ? (
            <Calendar
              {...common}
              key={calendarKey}
              mode="range"
              value={
                calendarValue && typeof calendarValue === "object"
                  ? calendarValue
                  : null
              }
              onValueChange={select}
            />
          ) : (
            <Calendar
              {...common}
              key={calendarKey}
              value={typeof calendarValue === "string" ? calendarValue : null}
              onValueChange={select}
            />
          )}
        </div>
        {error && (
          <p className="cr-date-picker-error" role="alert">
            {error}
          </p>
        )}
      </div>
      {(clearable || !autoApply) && (
        <div className="cr-date-picker-footer">
          {clearable && (
            <Button
              variant="ghost"
              size="sm"
              disabled={disabled || (!startInput && !endInput)}
              onClick={() =>
                select(props.mode === "range" ? null : "", false, true)
              }
            >
              {labels.clear}
            </Button>
          )}
          {!autoApply && (
            <div className="cr-date-picker-actions">
              <Button
                variant="ghost"
                size="sm"
                disabled={disabled}
                onClick={() => {
                  setDraft(chosen);
                  setSelectionPending(false);
                  setCalendarKey((current) => current + 1);
                  setStartInput(getStart(chosen));
                  setEndInput(getEnd(chosen));
                  setError("");
                  if (!inline) setOpen(false);
                }}
              >
                {labels.cancel}
              </Button>
              <Button
                size="sm"
                disabled={
                  disabled || selectionPending || !!error || !valid(draft)
                }
                onClick={() => {
                  commit(draft);
                  if (!inline) setOpen(false);
                }}
              >
                {labels.apply}
              </Button>
            </div>
          )}
        </div>
      )}
    </>
  );
  if (inline)
    return (
      <div
        ref={root}
        className={cx("cr-date-picker cr-date-picker-inline", className)}
        role="group"
        aria-label={label}
      >
        {fields}
        {content}
      </div>
    );
  return (
    <div ref={root} className={cx("cr-date-picker", className)}>
      {fields}
      <Base.Root
        open={open}
        onOpenChange={setOpen}
        modal={overlay ? true : "trap-focus"}
      >
        <Base.Trigger
          className={cx("cr-button cr-date-picker-trigger", triggerClassName)}
          data-variant="outline"
          disabled={disabled}
          aria-label={`${label}${display ? `: ${display}` : ""}`}
        >
          {props.renderTrigger ? (
            props.renderTrigger(display, placeholder)
          ) : (
            <>
              <span data-placeholder={!display || undefined}>
                {display || placeholder}
              </span>
              {props.icon ?? <CalendarDays size={16} aria-hidden="true" />}
            </>
          )}
        </Base.Trigger>
        <Base.Portal container={container}>
          {overlay && <Base.Backdrop className="cr-date-picker-backdrop" />}
          <Base.Positioner
            sideOffset={8}
            collisionPadding={16}
            collisionAvoidance={{ side: "shift", align: "shift" }}
            className="cr-positioner cr-date-picker-positioner"
          >
            <Base.Popup
              className="cr-popup cr-date-picker-popup"
              // Focus the first control (Close), keeping month controls visible on opening.
              initialFocus={true}
            >
              <div className="cr-date-picker-heading">
                <Base.Title>{label}</Base.Title>
                <Base.Close
                  className="cr-date-picker-close"
                  aria-label={labels.close}
                >
                  <X size={16} aria-hidden="true" />
                </Base.Close>
              </div>
              {content}
            </Base.Popup>
          </Base.Positioner>
        </Base.Portal>
      </Base.Root>
    </div>
  );
}
