// packages/vue/src/components/dropdown.vue
<script setup lang="ts">
import {
  DropdownMenuRoot,
  DropdownMenuTrigger,
  DropdownMenuPortal,
  DropdownMenuContent,
  DropdownMenuItem,
} from "reka-ui";
import type { Component } from "vue";
import { usePortalContainer } from "./utils";
import { RenderContent, useDisplayModel } from "./display-utils";
import type { DisplayContent, MenuAction } from "./display-types";
defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    trigger?: DisplayContent;
    triggerRender?: Component;
    items: MenuAction[];
    disabled?: boolean;
    side?: "top" | "bottom" | "left" | "right";
    align?: "start" | "center" | "end";
    emptyMessage?: DisplayContent;
    open?: boolean;
    defaultOpen?: boolean;
    modal?: boolean;
  }>(),
  {
    disabled: false,
    side: "bottom",
    align: "start",
    emptyMessage: "No actions available.",
    open: undefined,
    defaultOpen: false,
    modal: true,
  },
);
const emit = defineEmits<{
  "update:open": [value: boolean];
  "open-change": [value: boolean];
  select: [item: MenuAction];
}>();
const expanded = useDisplayModel(
  () => props.open,
  props.defaultOpen,
  (value) => {
    emit("update:open", value);
    emit("open-change", value);
  },
);
const container = usePortalContainer();
function select(item: MenuAction) {
  if (item.disabled) return;
  item.onSelect?.();
  emit("select", item);
}
</script>
<template>
  <DropdownMenuRoot v-model:open="expanded" :modal="modal"
    ><DropdownMenuTrigger
      :as-child="!!($slots.trigger || triggerRender)"
      :disabled="disabled"
      class="cr-button"
      data-variant="outline"
      ><slot name="trigger"
        ><component :is="triggerRender" v-if="triggerRender"
          ><RenderContent :content="trigger" /></component
        ><template v-else
          ><RenderContent :content="trigger" /><svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.75"
            aria-hidden="true"
          >
            <path
              d="m6 9 6 6 6-6"
            /></svg></template></slot></DropdownMenuTrigger
    ><DropdownMenuPortal :to="container"
      ><DropdownMenuContent
        v-bind="$attrs"
        :side="side"
        :align="align"
        :side-offset="6"
        class="cr-popup"
        ><p v-if="!items.length" class="cr-description">
          <slot name="empty"><RenderContent :content="emptyMessage" /></slot>
        </p>
        <DropdownMenuItem
          v-for="(item, index) in items"
          :key="item.id ?? index"
          :as="item.href && !item.disabled ? 'a' : 'div'"
          :href="item.disabled ? undefined : item.href"
          :disabled="item.disabled"
          :data-destructive="item.destructive || undefined"
          class="cr-menu-item"
          @select="select(item)"
          ><slot name="item" :item="item">{{
            item.label
          }}</slot></DropdownMenuItem
        ></DropdownMenuContent
      ></DropdownMenuPortal
    ></DropdownMenuRoot
  >
</template>

// packages/react/src/components/dropdown.tsx
"use client";
import { Menu as Base } from "@base-ui/react/menu";
import type { ComponentProps, ReactNode } from "react";
import { usePortalContainer } from "./utils";
export interface MenuAction {
  id?: string;
  label: string;
  onSelect?: () => void;
  href?: string;
  disabled?: boolean;
  destructive?: boolean;
}
export function Dropdown({
  trigger,
  triggerRender,
  items,
  disabled = false,
  side = "bottom",
  align = "start",
  emptyMessage = "No actions available.",
  ...rootProps
}: Omit<ComponentProps<typeof Base.Root>, "children"> & {
  trigger?: ReactNode;
  triggerRender?: ComponentProps<typeof Base.Trigger>["render"];
  items: MenuAction[];
  disabled?: boolean;
  side?: ComponentProps<typeof Base.Positioner>["side"];
  align?: ComponentProps<typeof Base.Positioner>["align"];
  emptyMessage?: ReactNode;
}) {
  const container = usePortalContainer();
  return (
    <Base.Root {...rootProps}>
      <Base.Trigger
        render={triggerRender}
        disabled={disabled}
        className="cr-button"
        data-variant="outline"
      >
        {trigger}
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.75"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </Base.Trigger>
      <Base.Portal container={container}>
        <Base.Positioner
          side={side}
          align={align}
          sideOffset={6}
          className="cr-positioner"
        >
          <Base.Popup className="cr-popup">
            {!items.length && <p className="cr-description">{emptyMessage}</p>}
            {items.map((item, index) => (
              <Base.Item
                key={item.id ?? index}
                render={
                  item.href && !item.disabled ? (
                    <a href={item.href}>{item.label}</a>
                  ) : undefined
                }
                className="cr-menu-item"
                data-destructive={item.destructive || undefined}
                disabled={item.disabled}
                onClick={item.onSelect}
              >
                {item.label}
              </Base.Item>
            ))}
          </Base.Popup>
        </Base.Positioner>
      </Base.Portal>
    </Base.Root>
  );
}
