// packages/vue/src/components/navigation-menu.vue
<script setup lang="ts">
import {
  NavigationMenuRoot,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuLink,
  NavigationMenuViewport,
} from "reka-ui";
import { computed } from "vue";
import { useDisplayModel } from "./display-utils";
const props = withDefaults(
  defineProps<{
    label?: string;
    value?: string | null;
    modelValue?: string | null;
    defaultValue?: string | null;
    items: Array<{
      value?: string;
      label: string;
      links: Array<{
        label: string;
        href: string;
        description?: string;
        active?: boolean;
      }>;
    }>;
  }>(),
  { label: "Main navigation" },
);
const emit = defineEmits<{
  "update:modelValue": [value: string | null];
  "update:value": [value: string | null];
  "value-change": [value: string | null];
}>();
const selected = useDisplayModel(
  () => (props.modelValue !== undefined ? props.modelValue : props.value),
  props.defaultValue ?? null,
  (value) => {
    emit("update:modelValue", value);
    emit("update:value", value);
    emit("value-change", value);
  },
);
const model = computed({
  get: () => selected.value ?? "",
  set: (value: string) => {
    selected.value = value || null;
  },
});
</script>
<template>
  <NavigationMenuRoot v-model="model" class="cr-navigation" :aria-label="label"
    ><NavigationMenuList class="cr-navigation-list"
      ><NavigationMenuItem
        v-for="(item, index) in items"
        :key="item.value ?? index"
        :value="item.value ?? String(index)"
        ><NavigationMenuTrigger class="cr-button" data-variant="ghost"
          >{{ item.label }}
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.75"
            aria-hidden="true"
          >
            <path d="m6 9 6 6 6-6" /></svg></NavigationMenuTrigger
        ><NavigationMenuContent class="cr-navigation-content"
          ><NavigationMenuLink
            v-for="link in item.links"
            :key="link.href"
            :href="link.href"
            :active="link.active"
            class="cr-navigation-link"
            @select="selected = null"
            ><strong>{{ link.label }}</strong
            ><span v-if="link.description">{{
              link.description
            }}</span></NavigationMenuLink
          ></NavigationMenuContent
        ></NavigationMenuItem
      ></NavigationMenuList
    >
    <div class="cr-vue-navigation-positioner">
      <NavigationMenuViewport class="cr-popup" /></div
  ></NavigationMenuRoot>
</template>

// packages/react/src/components/navigation-menu.tsx
"use client";
import { NavigationMenu as Base } from "@base-ui/react/navigation-menu";
import { usePortalContainer } from "./utils";
export function NavigationMenu({
  label = "Main navigation",
  items,
  value,
  defaultValue,
  onValueChange,
}: {
  label?: string;
  value?: string | null;
  defaultValue?: string | null;
  onValueChange?: (value: string | null) => void;
  items: Array<{
    value?: string;
    label: string;
    links: Array<{
      label: string;
      href: string;
      description?: string;
      active?: boolean;
    }>;
  }>;
}) {
  const container = usePortalContainer();
  return (
    <Base.Root
      value={value}
      defaultValue={defaultValue}
      onValueChange={onValueChange}
      className="cr-navigation"
      aria-label={label}
    >
      <Base.List className="cr-navigation-list">
        {items.map((item, index) => (
          <Base.Item
            key={item.value ?? index}
            value={item.value ?? String(index)}
          >
            <Base.Trigger className="cr-button" data-variant="ghost">
              {item.label}{" "}
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.75"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="m6 9 6 6 6-6" />
              </svg>
            </Base.Trigger>
            <Base.Content className="cr-navigation-content">
              {item.links.map((link) => (
                <Base.Link
                  key={link.href}
                  href={link.href}
                  active={link.active}
                  closeOnClick
                  className="cr-navigation-link"
                >
                  <strong>{link.label}</strong>
                  {link.description && <span>{link.description}</span>}
                </Base.Link>
              ))}
            </Base.Content>
          </Base.Item>
        ))}
      </Base.List>
      <Base.Portal container={container}>
        <Base.Positioner sideOffset={8} className="cr-positioner">
          <Base.Popup className="cr-popup">
            <Base.Viewport />
          </Base.Popup>
        </Base.Positioner>
      </Base.Portal>
    </Base.Root>
  );
}
