// packages/vue/src/components/table.vue
<script setup lang="ts">
import type { DisplayContent } from "./display-types";
import { RenderContent } from "./display-utils";
withDefaults(
  defineProps<{
    caption: string;
    columns: string[];
    rows: DisplayContent[][];
    loading?: boolean;
    loadingMessage?: DisplayContent;
    emptyMessage?: DisplayContent;
    getRowKey?: (row: DisplayContent[], index: number) => string | number;
  }>(),
  {
    loading: false,
    loadingMessage: "Loading records…",
    emptyMessage: "No records yet.",
  },
);
</script>
<template>
  <div class="cr-table-scroll" role="region" :aria-label="caption" tabindex="0">
    <table class="cr-table" :aria-busy="loading || undefined">
      <caption>
        {{
          caption
        }}
      </caption>
      <thead>
        <tr>
          <th v-for="(column, index) in columns" :key="index" scope="col">
            <slot name="header" :column="column" :index="index">{{
              column
            }}</slot>
          </th>
        </tr>
      </thead>
      <tbody>
        <template v-if="!loading"
          ><tr
            v-for="(row, index) in rows"
            :key="getRowKey?.(row, index) ?? index"
          >
            <td v-for="(value, column) in row" :key="column">
              <slot
                name="cell"
                :value="value"
                :row="row"
                :row-index="index"
                :column-index="column"
                ><RenderContent :content="value"
              /></slot>
            </td></tr
        ></template>
        <tr v-if="loading || !rows.length">
          <td :colspan="Math.max(1, columns.length)">
            <slot v-if="loading" name="loading"
              ><RenderContent :content="loadingMessage" /></slot
            ><slot v-else name="empty"
              ><RenderContent :content="emptyMessage"
            /></slot>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// packages/react/src/components/table.tsx
"use client";
/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- The named overflow region needs a tab stop for keyboard scrolling. */
import type { ReactNode } from "react";
export function Table({
  caption,
  columns,
  rows,
  loading = false,
  loadingMessage = "Loading records…",
  emptyMessage = "No records yet.",
  getRowKey,
}: {
  caption: string;
  columns: string[];
  rows: ReactNode[][];
  loading?: boolean;
  loadingMessage?: ReactNode;
  emptyMessage?: ReactNode;
  getRowKey?: (row: ReactNode[], index: number) => string | number;
}) {
  return (
    <div
      className="cr-table-scroll"
      role="region"
      aria-label={caption}
      tabIndex={0}
    >
      <table className="cr-table" aria-busy={loading || undefined}>
        <caption>{caption}</caption>
        <thead>
          <tr>
            {columns.map((column, index) => (
              <th key={index} scope="col">
                {column}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {!loading &&
            rows.map((row, index) => (
              <tr key={getRowKey?.(row, index) ?? index}>
                {row.map((value, column) => (
                  <td key={column}>{value}</td>
                ))}
              </tr>
            ))}
          {(loading || !rows.length) && (
            <tr>
              <td colSpan={Math.max(1, columns.length)}>
                {loading ? loadingMessage : emptyMessage}
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
