// packages/react/src/components/avatar.tsx
"use client";
import type { ComponentProps, CSSProperties } from "react";
import { Avatar as Base } from "@base-ui/react/avatar";
import { cx } from "./utils";
export function Avatar({
  src,
  name,
  size = 36,
  className,
  style,
  ...props
}: Omit<
  ComponentProps<typeof Base.Root>,
  "className" | "children" | "style"
> & {
  src?: string;
  name: string;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const initials =
    name
      .trim()
      .split(/\s+/)
      .slice(0, 2)
      .map((word) => Array.from(word)[0] ?? "")
      .join("")
      .toLocaleUpperCase() || "?";
  return (
    <Base.Root
      {...props}
      className={cx("cr-avatar", className)}
      style={{ width: size, height: size, ...style }}
    >
      <Base.Image src={src} alt={name} className="cr-avatar-image" />
      <Base.Fallback role="img" aria-label={name || "Avatar"}>
        {initials}
      </Base.Fallback>
    </Base.Root>
  );
}

// packages/vue/src/components/avatar.vue
<script setup lang="ts">
import { computed } from "vue";
import { AvatarRoot, AvatarImage, AvatarFallback } from "reka-ui";
const props = withDefaults(
  defineProps<{
    src?: string;
    name: string;
    size?: number;
    className?: string;
  }>(),
  { size: 36 },
);
const initials = computed(
  () =>
    props.name
      .trim()
      .split(/\s+/)
      .slice(0, 2)
      .map((word) => Array.from(word)[0] ?? "")
      .join("")
      .toLocaleUpperCase() || "?",
);
</script>
<template>
  <AvatarRoot
    :class="['cr-avatar', className]"
    :style="{ width: `${size}px`, height: `${size}px` }"
    ><AvatarImage
      :src="src ?? ''"
      :alt="name"
      class="cr-avatar-image"
    /><AvatarFallback role="img" :aria-label="name || 'Avatar'"
      ><slot name="fallback">{{ initials }}</slot></AvatarFallback
    ></AvatarRoot
  >
</template>
